<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AgressorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbagressor')->insert([
            [
                'id' => 1,
                'imagemAgressor' => 'imagens/agressores/marcos-antonio-vieira.jpg',
                'nomeAgressor' => 'Marcos Antônio Vieira',
                'cpfAgressor' => '073.375.433-36',
                'logradouroAgressor' => 'Rua Feliciano de Mendonça',
                'numLogradouroAgressor' => '212',
                'bairroAgressor' => 'Guaianases',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Casa 2',
                'dataNascimentoAgressor' => '1972-04-11',
                'statusAgressor' => 'Monitorado',
                'idTornozeleira' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'imagemAgressor' => 'imagens/agressores/roberto-carlos-almeida.jpg',
                'nomeAgressor' => 'Roberto Carlos Almeida',
                'cpfAgressor' => '036.541.458-17',
                'logradouroAgressor' => 'Rua Augusta',
                'numLogradouroAgressor' => '1580',
                'bairroAgressor' => 'Consolação',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Apto 92',
                'dataNascimentoAgressor' => '1981-10-03',
                'statusAgressor' => 'Monitorado',
                'idTornozeleira' => 2,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'imagemAgressor' => 'imagens/agressores/jose-eduardo-pacheco.jpg',
                'nomeAgressor' => 'José Eduardo Pacheco',
                'cpfAgressor' => '685.014.294-14',
                'logradouroAgressor' => 'Avenida Souza Ramos',
                'numLogradouroAgressor' => '740',
                'bairroAgressor' => 'Cidade Tiradentes',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Bloco D',
                'dataNascimentoAgressor' => '1989-07-19',
                'statusAgressor' => 'Preso',
                'idTornozeleira' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'imagemAgressor' => 'imagens/agressores/anderson-luiz-ferreira.jpg',
                'nomeAgressor' => 'Anderson Luiz Ferreira',
                'cpfAgressor' => '019.655.698-89',
                'logradouroAgressor' => 'Rua Tuiuti',
                'numLogradouroAgressor' => '1425',
                'bairroAgressor' => 'Tatuapé',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Fundos',
                'dataNascimentoAgressor' => '1994-01-28',
                'statusAgressor' => 'Monitorado',
                'idTornozeleira' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'imagemAgressor' => 'imagens/agressores/paulo-sergio-andrade.jpg',
                'nomeAgressor' => 'Paulo Sérgio Andrade',
                'cpfAgressor' => '169.340.608-06',
                'logradouroAgressor' => 'Rua Ernesto Nazareth',
                'numLogradouroAgressor' => '88',
                'bairroAgressor' => 'Capão Redondo',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Casa 3',
                'dataNascimentoAgressor' => '1976-11-30',
                'statusAgressor' => 'Inativo',
                'idTornozeleira' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'imagemAgressor' => 'imagens/agressores/wagner-oliveira-brito.jpg',
                'nomeAgressor' => 'Wagner Oliveira Brito',
                'cpfAgressor' => '835.615.951-20',
                'logradouroAgressor' => 'Rua Coronel José Venâncio Dias',
                'numLogradouroAgressor' => '306',
                'bairroAgressor' => 'Freguesia do Ó',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Apto 14',
                'dataNascimentoAgressor' => '1986-05-07',
                'statusAgressor' => 'Monitorado',
                'idTornozeleira' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'imagemAgressor' => 'imagens/agressores/sidney-rocha-menezes.jpg',
                'nomeAgressor' => 'Sidney Rocha Menezes',
                'cpfAgressor' => '484.656.482-71',
                'logradouroAgressor' => 'Rua Comendador Elias Zarzur',
                'numLogradouroAgressor' => '1190',
                'bairroAgressor' => 'Sapopemba',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Casa 4',
                'dataNascimentoAgressor' => '1968-08-15',
                'statusAgressor' => 'Foragido',
                'idTornozeleira' => 7,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'imagemAgressor' => 'imagens/agressores/rogerio-batista-lima.jpg',
                'nomeAgressor' => 'Rogério Batista Lima',
                'cpfAgressor' => '366.299.468-20',
                'logradouroAgressor' => 'Avenida Carlos Caldeira Filho',
                'numLogradouroAgressor' => '2210',
                'bairroAgressor' => 'Campo Limpo',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Apto 803',
                'dataNascimentoAgressor' => '1997-02-24',
                'statusAgressor' => 'Monitorado',
                'idTornozeleira' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'imagemAgressor' => 'imagens/agressores/cleber-dos-santos-nunes.jpg',
                'nomeAgressor' => 'Cleber dos Santos Nunes',
                'cpfAgressor' => '044.369.957-71',
                'logradouroAgressor' => 'Rua João Marcelino Branco',
                'numLogradouroAgressor' => '57',
                'bairroAgressor' => 'Pirituba',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Apartamento 502',
                'dataNascimentoAgressor' => '1990-12-09',
                'statusAgressor' => 'Preso',
                'idTornozeleira' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'imagemAgressor' => 'imagens/agressores/everton-maciel-duarte.jpg',
                'nomeAgressor' => 'Everton Maciel Duarte',
                'cpfAgressor' => '773.872.148-08',
                'logradouroAgressor' => 'Estrada do Itaquera',
                'numLogradouroAgressor' => '3488',
                'bairroAgressor' => 'Jardim Ângela',
                'cidadeAgressor' => 'São Paulo',
                'ufAgressor' => 'SP',
                'complementoAgressor' => 'Casa B',
                'dataNascimentoAgressor' => '1983-03-02',
                'statusAgressor' => 'Monitorado',
                'idTornozeleira' => 10,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
