<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AutoridadeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbautoridade')->insert([
            [
                'id' => 1,
                'nomeAutoridade' => 'Raven',
                'imagemAutoridade' => 'iaciasi.png',
                'emailAutoridade' => 'raven.oficial.tcc@gmail.com',
                'cpfAutoridade' => '123.456.789-00',
                'matriculaAutoridade' => '123456789',
                'cargoAutoridade' => 'Administrador',
                'unidadeAutoridade' => 'Unidade Administrativa',
                'senhaAutoridade' => Hash::make('RavenTcc'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'nomeAutoridade' => 'Raven_TCC',
                'imagemAutoridade' => 'iaciasi.png',
                'emailAutoridade' => 'raven@gmail.com',
                'cpfAutoridade' => '123.456.789-01',
                'matriculaAutoridade' => '123456781',
                'cargoAutoridade' => 'Administrador',
                'unidadeAutoridade' => 'Unidade Administrativa',
                'senhaAutoridade' => Hash::make('RavenTcc_118'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'nomeAutoridade' => 'Helena Marques Villela',
                'imagemAutoridade' => 'imagens/autoridades/helena-villela.jpg',
                'emailAutoridade' => 'helena.villela@policiacivil.sp.gov.br',
                'cpfAutoridade' => '039.117.182-84',
                'matriculaAutoridade' => 'PC-204518',
                'cargoAutoridade' => 'Delegada de Polícia',
                'unidadeAutoridade' => '1ª Delegacia de Defesa da Mulher - Centro',
                'senhaAutoridade' => Hash::make('Helena@2026'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'nomeAutoridade' => 'Ricardo Salles Pimentel',
                'imagemAutoridade' => 'imagens/autoridades/ricardo-pimentel.jpg',
                'emailAutoridade' => 'ricardo.pimentel@policiacivil.sp.gov.br',
                'cpfAutoridade' => '278.248.963-15',
                'matriculaAutoridade' => 'PC-198340',
                'cargoAutoridade' => 'Investigador de Polícia',
                'unidadeAutoridade' => '2ª Delegacia de Defesa da Mulher - Santo Amaro',
                'senhaAutoridade' => Hash::make('Ricardo@2026'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'nomeAutoridade' => 'Cristiane Duarte Bastos',
                'imagemAutoridade' => 'imagens/autoridades/cristiane-bastos.jpg',
                'emailAutoridade' => 'cristiane.bastos@policiacivil.sp.gov.br',
                'cpfAutoridade' => '834.657.871-70',
                'matriculaAutoridade' => 'PC-221074',
                'cargoAutoridade' => 'Escrivã de Polícia',
                'unidadeAutoridade' => '3ª Delegacia de Defesa da Mulher - Itaquera',
                'senhaAutoridade' => Hash::make('Cristiane@2026'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'nomeAutoridade' => 'Anderson Paiva Rezende',
                'imagemAutoridade' => 'imagens/autoridades/anderson-rezende.jpg',
                'emailAutoridade' => 'anderson.rezende@pm.sp.gov.br',
                'cpfAutoridade' => '331.509.839-59',
                'matriculaAutoridade' => 'PM-113877',
                'cargoAutoridade' => 'Sargento da Polícia Militar',
                'unidadeAutoridade' => '9º Batalhão de Polícia Militar Metropolitano',
                'senhaAutoridade' => Hash::make('Anderson@2026'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'nomeAutoridade' => 'Mônica Araújo Bezerril',
                'imagemAutoridade' => 'imagens/autoridades/monica-bezerril.jpg',
                'emailAutoridade' => 'monica.bezerril@pm.sp.gov.br',
                'cpfAutoridade' => '301.031.051-07',
                'matriculaAutoridade' => 'PM-127004',
                'cargoAutoridade' => 'Tenente da Polícia Militar',
                'unidadeAutoridade' => 'Patrulha Maria da Penha - Comando de Policiamento Leste',
                'senhaAutoridade' => Hash::make('Monica@2026'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'nomeAutoridade' => 'Eduardo Rossi Caldeira',
                'imagemAutoridade' => 'imagens/autoridades/eduardo-caldeira.jpg',
                'emailAutoridade' => 'eduardo.caldeira@policiacivil.sp.gov.br',
                'cpfAutoridade' => '834.738.299-94',
                'matriculaAutoridade' => 'PC-176622',
                'cargoAutoridade' => 'Delegado Titular',
                'unidadeAutoridade' => '4ª Delegacia de Defesa da Mulher - Guaianases',
                'senhaAutoridade' => Hash::make('Eduardo@2026'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'nomeAutoridade' => 'Tânia Regina Lourenço',
                'imagemAutoridade' => 'imagens/autoridades/tania-lourenco.jpg',
                'emailAutoridade' => 'tania.lourenco@policiacivil.sp.gov.br',
                'cpfAutoridade' => '737.631.165-32',
                'matriculaAutoridade' => 'PC-233190',
                'cargoAutoridade' => 'Agente de Telemática',
                'unidadeAutoridade' => 'Central de Monitoramento Eletrônico - SAP',
                'senhaAutoridade' => Hash::make('Tania@2026'),
                'statusAutoridade' => 'Ativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'nomeAutoridade' => 'Bruno Kenji Yamashita',
                'imagemAutoridade' => 'imagens/autoridades/bruno-yamashita.jpg',
                'emailAutoridade' => 'bruno.yamashita@policiacivil.sp.gov.br',
                'cpfAutoridade' => '667.010.651-39',
                'matriculaAutoridade' => 'PC-190455',
                'cargoAutoridade' => 'Investigador de Polícia',
                'unidadeAutoridade' => 'Central de Monitoramento Eletrônico - SAP',
                'senhaAutoridade' => Hash::make('Bruno@2026'),
                'statusAutoridade' => 'Inativo',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
