<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DelegaciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbdelegacia')->insert([
            [
                'id' => 1,
                'nomeDelegacia' => '1ª Delegacia de Defesa da Mulher - Centro',
                'tipoDelegacia' => 'Delegacia de Defesa da Mulher',
                'statusDelegacia' => 'Ativa - atendimento 24 horas',
                'logradouroDelegacia' => 'Rua Doutor Bittencourt Rodrigues',
                'numLogradouroDelegacia' => '200',
                'bairroDelegacia' => 'Sé',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '01017-010',
                'latitudedelegacia' => -23.5489420,
                'longitudedelegacia' => -46.6337310,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'nomeDelegacia' => '2ª Delegacia de Defesa da Mulher - Santo Amaro',
                'tipoDelegacia' => 'Delegacia de Defesa da Mulher',
                'statusDelegacia' => 'Ativa - horário comercial',
                'logradouroDelegacia' => 'Rua Doutor Rubens Meireles',
                'numLogradouroDelegacia' => '87',
                'bairroDelegacia' => 'Santo Amaro',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '04743-030',
                'latitudedelegacia' => -23.6501880,
                'longitudedelegacia' => -46.7043270,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'nomeDelegacia' => '3ª Delegacia de Defesa da Mulher - Itaquera',
                'tipoDelegacia' => 'Delegacia de Defesa da Mulher',
                'statusDelegacia' => 'Ativa - atendimento 24 horas',
                'logradouroDelegacia' => 'Avenida Itaquera',
                'numLogradouroDelegacia' => '3150',
                'bairroDelegacia' => 'Itaquera',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '08210-000',
                'latitudedelegacia' => -23.5402190,
                'longitudedelegacia' => -46.4561440,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'nomeDelegacia' => '4ª Delegacia de Defesa da Mulher - Guaianases',
                'tipoDelegacia' => 'Delegacia de Defesa da Mulher',
                'statusDelegacia' => 'Ativa - horário comercial',
                'logradouroDelegacia' => 'Rua Feliciano de Mendonça',
                'numLogradouroDelegacia' => '1100',
                'bairroDelegacia' => 'Guaianases',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '08460-365',
                'latitudedelegacia' => -23.5451260,
                'longitudedelegacia' => -46.4108950,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'nomeDelegacia' => '5ª Delegacia de Defesa da Mulher - Butantã',
                'tipoDelegacia' => 'Delegacia de Defesa da Mulher',
                'statusDelegacia' => 'Ativa - horário comercial',
                'logradouroDelegacia' => 'Avenida Corifeu de Azevedo Marques',
                'numLogradouroDelegacia' => '2450',
                'bairroDelegacia' => 'Butantã',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '05581-001',
                'latitudedelegacia' => -23.5721340,
                'longitudedelegacia' => -46.7318060,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'nomeDelegacia' => '32º Distrito Policial - Itaquera',
                'tipoDelegacia' => 'Distrito Policial',
                'statusDelegacia' => 'Ativa - atendimento 24 horas',
                'logradouroDelegacia' => 'Rua Amabile Turchi Ferrari',
                'numLogradouroDelegacia' => '35',
                'bairroDelegacia' => 'Itaquera',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '08220-140',
                'latitudedelegacia' => -23.5364510,
                'longitudedelegacia' => -46.4620780,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'nomeDelegacia' => '49º Distrito Policial - São Mateus',
                'tipoDelegacia' => 'Distrito Policial',
                'statusDelegacia' => 'Ativa - atendimento 24 horas',
                'logradouroDelegacia' => 'Avenida Ragueb Chohfi',
                'numLogradouroDelegacia' => '1856',
                'bairroDelegacia' => 'São Mateus',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '08375-000',
                'latitudedelegacia' => -23.6103790,
                'longitudedelegacia' => -46.4674520,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'nomeDelegacia' => '89º Distrito Policial - Portal do Morumbi',
                'tipoDelegacia' => 'Distrito Policial',
                'statusDelegacia' => 'Ativa - horário comercial',
                'logradouroDelegacia' => 'Avenida Giovanni Gronchi',
                'numLogradouroDelegacia' => '5930',
                'bairroDelegacia' => 'Vila Andrade',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '05724-003',
                'latitudedelegacia' => -23.6297410,
                'longitudedelegacia' => -46.7361880,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'nomeDelegacia' => 'Delegacia Eletrônica da Mulher - Plantão Online',
                'tipoDelegacia' => 'Delegacia Eletrônica',
                'statusDelegacia' => 'Ativa - atendimento remoto 24 horas',
                'logradouroDelegacia' => 'Rua Brigadeiro Tobias',
                'numLogradouroDelegacia' => '527',
                'bairroDelegacia' => 'Luz',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '01032-000',
                'latitudedelegacia' => -23.5364320,
                'longitudedelegacia' => -46.6345170,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'nomeDelegacia' => '70º Distrito Policial - Vila Ema',
                'tipoDelegacia' => 'Distrito Policial',
                'statusDelegacia' => 'Em reforma - atendimento provisório no 57º DP',
                'logradouroDelegacia' => 'Rua Dionísio da Costa',
                'numLogradouroDelegacia' => '430',
                'bairroDelegacia' => 'Vila Ema',
                'cidadeDelegacia' => 'São Paulo',
                'ufDelegacia' => 'SP',
                'cepDelegacia' => '03283-000',
                'latitudedelegacia' => -23.5893640,
                'longitudedelegacia' => -46.5424190,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
