<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EnderecoVitimaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbenderecovitima')->insert([
            [
                'logradouroVitima' => 'Rua Inácio Moreira',
                'numLogradouroVitima' => '444',
                'bairroVitima' => 'Guaianases',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => null,
                'cepVitima' => '08460-300',
                'idVitima' => 1,
                'latitudeVitima' => -23.550093,
                'longitudeVitima' => -46.400124,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Rua Coronel Xavier de Toledo',
                'numLogradouroVitima' => '132',
                'bairroVitima' => 'República',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => 'Apto 74',
                'cepVitima' => '01048-100',
                'idVitima' => 2,
                'latitudeVitima' => -23.5460210,
                'longitudeVitima' => -46.6395470,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Avenida dos Metalúrgicos',
                'numLogradouroVitima' => '1890',
                'bairroVitima' => 'Cidade Tiradentes',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => 'Bloco C, Apto 32',
                'cepVitima' => '08471-000',
                'idVitima' => 3,
                'latitudeVitima' => -23.5847130,
                'longitudeVitima' => -46.4026880,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Rua Serra de Botucatu',
                'numLogradouroVitima' => '2075',
                'bairroVitima' => 'Tatuapé',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => 'Casa 2 - fundos',
                'cepVitima' => '03317-000',
                'idVitima' => 4,
                'latitudeVitima' => -23.5548390,
                'longitudeVitima' => -46.5651240,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Rua Baltazar dos Reis',
                'numLogradouroVitima' => '318',
                'bairroVitima' => 'Capão Redondo',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => null,
                'cepVitima' => '05865-190',
                'idVitima' => 5,
                'latitudeVitima' => -23.6645720,
                'longitudeVitima' => -46.7609310,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Avenida Itaberaba',
                'numLogradouroVitima' => '1044',
                'bairroVitima' => 'Freguesia do Ó',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => 'Apto 121, Torre B',
                'cepVitima' => '02734-000',
                'idVitima' => 6,
                'latitudeVitima' => -23.4936480,
                'longitudeVitima' => -46.6837590,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Rua Sapopemba',
                'numLogradouroVitima' => '7260',
                'bairroVitima' => 'Sapopemba',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => null,
                'cepVitima' => '03977-000',
                'idVitima' => 7,
                'latitudeVitima' => -23.6011940,
                'longitudeVitima' => -46.5163720,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Rua Nossa Senhora do Bom Conselho',
                'numLogradouroVitima' => '95',
                'bairroVitima' => 'Campo Limpo',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => 'Apto 44',
                'cepVitima' => '05781-000',
                'idVitima' => 8,
                'latitudeVitima' => -23.6482350,
                'longitudeVitima' => -46.7593410,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Avenida Mutinga',
                'numLogradouroVitima' => '2830',
                'bairroVitima' => 'Pirituba',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => null,
                'cepVitima' => '05110-000',
                'idVitima' => 9,
                'latitudeVitima' => -23.4871560,
                'longitudeVitima' => -46.7305880,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'logradouroVitima' => 'Estrada do M\'Boi Mirim',
                'numLogradouroVitima' => '5190',
                'bairroVitima' => 'Jardim Ângela',
                'cidadeVitima' => 'São Paulo',
                'ufVitima' => 'SP',
                'complementoVitima' => 'Casa 1',
                'cepVitima' => '04935-000',
                'idVitima' => 10,
                'latitudeVitima' => -23.6902740,
                'longitudeVitima' => -46.7538190,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
