<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OcorrenciaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('tbocorrencia')->insert([
            [
                'id' => 1,
                'dataOcorrencia' => '2026-09-11',
                'dataHoraOcorrencia' => '2026-09-11 21:40:00',
                'descricaoOcorrencia' => 'Vítima acionou o botão de pânico após identificar o agressor parado em frente à residência. Equipe chegou ao local em 9 minutos e o agressor já havia se evadido.',
                'tipoOcorrencia' => 'Descumprimento de medida protetiva',
                'gravidadeOcorrencia' => 'Alta',
                'localOcorrencia' => 'Rua Inácio Moreira, 444',
                'bairroOcorrencia' => 'Guaianases',
                'statusAtendimento' => 'concluido',
                'idVitima' => 1,
                'idAgressor' => 1,
                'idAutoridade' => 3,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 2,
                'dataOcorrencia' => '2026-09-13',
                'dataHoraOcorrencia' => '2026-09-13 23:15:00',
                'descricaoOcorrencia' => 'Agressor permaneceu na calçada do prédio por mais de vinte minutos efetuando ligações insistentes. Conduzido ao distrito policial para lavratura do termo circunstanciado.',
                'tipoOcorrencia' => 'Perseguição (stalking)',
                'gravidadeOcorrencia' => 'Alta',
                'localOcorrencia' => 'Rua Coronel Xavier de Toledo, 132',
                'bairroOcorrencia' => 'República',
                'statusAtendimento' => 'concluido',
                'idVitima' => 2,
                'idAgressor' => 2,
                'idAutoridade' => 6,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 3,
                'dataOcorrencia' => '2026-09-08',
                'dataHoraOcorrencia' => '2026-09-08 05:10:00',
                'descricaoOcorrencia' => 'Rompimento da tornozeleira eletrônica registrado pela central. Agressor localizado horas depois na casa de um familiar e recolhido ao sistema prisional.',
                'tipoOcorrencia' => 'Violação de dispositivo de monitoramento',
                'gravidadeOcorrencia' => 'Alta',
                'localOcorrencia' => 'Avenida Souza Ramos, 740',
                'bairroOcorrencia' => 'Cidade Tiradentes',
                'statusAtendimento' => 'concluido',
                'idVitima' => 3,
                'idAgressor' => 3,
                'idAutoridade' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 4,
                'dataOcorrencia' => '2026-09-16',
                'dataHoraOcorrencia' => '2026-09-16 08:55:00',
                'descricaoOcorrencia' => 'Agressor abordado nas proximidades do local de trabalho da vítima. Alegou estar de passagem, mas o histórico de deslocamento contradisse a versão apresentada.',
                'tipoOcorrencia' => 'Descumprimento de medida protetiva',
                'gravidadeOcorrencia' => 'Média',
                'localOcorrencia' => 'Rua Serra de Botucatu, 2075',
                'bairroOcorrencia' => 'Tatuapé',
                'statusAtendimento' => 'andamento',
                'idVitima' => 4,
                'idAgressor' => 4,
                'idAutoridade' => 4,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 5,
                'dataOcorrencia' => '2026-06-30',
                'dataHoraOcorrencia' => '2026-06-30 15:45:00',
                'descricaoOcorrencia' => 'Falha prolongada no sinal do dispositivo. Verificação técnica não apontou indício de adulteração; equipamento substituído preventivamente.',
                'tipoOcorrencia' => 'Falha técnica de monitoramento',
                'gravidadeOcorrencia' => 'Baixa',
                'localOcorrencia' => 'Rua Baltazar dos Reis, 318',
                'bairroOcorrencia' => 'Capão Redondo',
                'statusAtendimento' => 'concluido',
                'idVitima' => 5,
                'idAgressor' => 5,
                'idAutoridade' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 6,
                'dataOcorrencia' => '2026-09-14',
                'dataHoraOcorrencia' => '2026-09-14 19:20:00',
                'descricaoOcorrencia' => 'Agressor tentou entrar no condomínio alegando visita a outro morador. Portaria reteve o acesso e acionou a Patrulha Maria da Penha.',
                'tipoOcorrencia' => 'Descumprimento de medida protetiva',
                'gravidadeOcorrencia' => 'Alta',
                'localOcorrencia' => 'Avenida Itaberaba, 1044',
                'bairroOcorrencia' => 'Freguesia do Ó',
                'statusAtendimento' => 'concluido',
                'idVitima' => 6,
                'idAgressor' => 6,
                'idAutoridade' => 7,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 7,
                'dataOcorrencia' => '2026-09-17',
                'dataHoraOcorrencia' => '2026-09-17 02:40:00',
                'descricaoOcorrencia' => 'Tornozeleira encontrada rompida em via pública. Vítima removida para endereço protegido e difusão de busca emitida para toda a região leste.',
                'tipoOcorrencia' => 'Violação de dispositivo de monitoramento',
                'gravidadeOcorrencia' => 'Alta',
                'localOcorrencia' => 'Rua Sapopemba, 7260',
                'bairroOcorrencia' => 'Sapopemba',
                'statusAtendimento' => 'andamento',
                'idVitima' => 7,
                'idAgressor' => 7,
                'idAutoridade' => 8,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 8,
                'dataOcorrencia' => '2026-09-18',
                'dataHoraOcorrencia' => '2026-09-18 06:30:00',
                'descricaoOcorrencia' => 'Dispositivo com bateria crítica por mais de doze horas. Agressor intimado a comparecer à central de monitoramento no mesmo dia.',
                'tipoOcorrencia' => 'Falha técnica de monitoramento',
                'gravidadeOcorrencia' => 'Média',
                'localOcorrencia' => 'Avenida Carlos Caldeira Filho, 2210',
                'bairroOcorrencia' => 'Campo Limpo',
                'statusAtendimento' => 'andamento',
                'idVitima' => 8,
                'idAgressor' => 8,
                'idAutoridade' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 9,
                'dataOcorrencia' => '2026-08-17',
                'dataHoraOcorrencia' => '2026-08-17 18:05:00',
                'descricaoOcorrencia' => 'Agressor localizado a poucos metros da residência da vítima, com histórico de ameaças por mensagem. Prisão preventiva representada e deferida dois dias depois.',
                'tipoOcorrencia' => 'Ameaça',
                'gravidadeOcorrencia' => 'Alta',
                'localOcorrencia' => 'Avenida Mutinga, 2830',
                'bairroOcorrencia' => 'Pirituba',
                'statusAtendimento' => 'concluido',
                'idVitima' => 9,
                'idAgressor' => 9,
                'idAutoridade' => 5,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'id' => 10,
                'dataOcorrencia' => '2026-09-18',
                'dataHoraOcorrencia' => '2026-09-18 14:10:00',
                'descricaoOcorrencia' => 'Alerta gerado por imprecisão de GPS em área de sombra de sinal. Conferência da trilha confirmou que o agressor estava fora da zona de exclusão.',
                'tipoOcorrencia' => 'Alerta improcedente',
                'gravidadeOcorrencia' => 'Baixa',
                'localOcorrencia' => 'Estrada do M\'Boi Mirim, 5190',
                'bairroOcorrencia' => 'Jardim Ângela',
                'statusAtendimento' => 'concluido',
                'idVitima' => 10,
                'idAgressor' => 10,
                'idAutoridade' => 9,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ]);
    }
}
