@extends('layouts.admin',['pageTitle'=>$c['label'],'active'=>$c['base']])
@section('admin-content')
<header class="admin-heading"><h1>{{ $c['label'] }}</h1></header><a class="admin-back" href="{{ route($c['base']) }}">‹ voltar</a>
<section class="admin-panel victim-detail">
<div class="victim-profile"><div class="victim-profile-heading"><h2>{{ $record->{'nome'.$c['suffix']} }}</h2><span class="status-neutral">{{ ucfirst($record->{'status'.$c['suffix']}) }}</span></div>
<dl class="victim-info"><div><dt>CPF:</dt><dd>{{ $record->{'cpf'.$c['suffix']} }}</dd></div><div><dt>Nascimento:</dt><dd>{{ \Carbon\Carbon::parse($record->{'dataNascimento'.$c['suffix']})->format('d/m/Y') }}</dd></div><div><dt>Telefone:</dt><dd>{{ $c['victim'] ? ($record->telefones()->first()?->numeroTelefoneVitima ?? '—') : ($record->telefoneAgressor ?? '—') }}</dd></div>@if($c['victim'])<div><dt>E-mail:</dt><dd>{{ $record->emailVitima }}</dd></div>@endif</dl>
<div class="victim-profile-actions"><a class="admin-action secondary" href="{{ route($c['base'].'.edit',$record->id) }}">editar info</a><form method="POST" action="{{ route($c['base'].'.status',$record->id) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $record->{'status'.$c['suffix']}==='ativo'?'inativo':'ativo' }}"><button class="admin-action">{{ $record->{'status'.$c['suffix']}==='ativo'?'Inativar':'Ativar' }}</button></form></div></div>
<div class="victim-related"><section><h2>Ocorrências</h2>@forelse($occurrences as $item)<p class="victim-related-empty"><a href="{{ route('admin.occurrences.show',$item->id) }}">{{ $item->tipoOcorrencia }} — {{ $item->dataOcorrencia }}</a></p>@empty<p class="victim-related-empty">Nenhuma ocorrência registrada.</p>@endforelse{{ $occurrences->links() }}</section>
@if($c['victim'])<section><h2>Locais de segurança</h2>@forelse($places as $place)<div class="victim-place-preview"><span>{{ $place->tipoSolicitacao }}<br>{{ $place->logradouroSolicitacao }}, {{ $place->numLogradouroSolicitacao }} — {{ $place->cidadeSolicitacao }}</span><form method="POST" action="{{ route('admin.places.remove',$place->id) }}">@csrf @method('DELETE')<button type="submit">excluir</button></form></div>@empty<p class="victim-related-empty">Nenhum local aprovado.</p>@endforelse</section>@endif
</div></section><div class="victim-detail-footer"><button onclick="window.print()" type="button">Imprimir / salvar PDF</button></div>
@endsection
